platform :ios, '12.2'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'crimedetection' do
  config = use_native_modules!

  # Use modular headers globally for all pods
  use_modular_headers!

  use_react_native!(
    :path => config[:reactNativePath],
    # Add any other React Native configurations if needed
  )

  # Specific Firebase dependencies with modular headers
  pod 'Firebase/Core', :modular_headers => true
  pod 'Firebase/Firestore', :modular_headers => true
  pod 'Firebase/Analytics', :modular_headers => true
  # Add more Firebase dependencies as needed

  target 'crimedetectionTests' do
    inherit! :complete
    # Pods for testing
  end
  #fill line
end
