platform :ios, '11.0'

target 'crimedetection' do
  use_frameworks!

  # Correct paths to React Native pods
  pod 'React-Core', :path => '../node_modules/react-native/ReactCommon'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'

  # Firebase or other dependencies
  pod 'Firebase/Core'

  post_install do |installer|
    react_native_post_install(installer)
  end
end
